export { assemble } from "./assembler.js";
export type { Assembled, AssembleResult, AssemblyError } from "./assembler.js";
export { decode, encode, FORMAS, signExtend } from "./isa.js";
export type { Format, Instruction, Mnemonic } from "./isa.js";
export { initialCpu, runCpu, stepCpu } from "./reference.js";
export type { CpuState } from "./reference.js";
export { cpuWorld } from "./datapath.js";
export type { EstadoBanco, EstadoMemoria, EstadoPc } from "./datapath.js";
export { CPU_VIEWS, VIEW_PROCESSADOR, VIEW_SISTEMA, viewSomador } from "./views.js";
export { porta, somadorCompleto, somadorWorld } from "./gates.js";
export type { PortaLogica } from "./gates.js";
